CREATE TABLE IF NOT EXISTS `afv_storyboard_video_quality` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `storyboard_item_id` bigint NOT NULL COMMENT 'Storyboard item ID',
  `video_task_id` bigint NULL DEFAULT NULL COMMENT 'Video generation task ID',
  `video_item_id` bigint NULL DEFAULT NULL COMMENT 'Video generation item ID',
  `video_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Candidate video URL',
  `cover_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Candidate cover URL',
  `prompt_snapshot` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Prompt used by this candidate',
  `total_score` int NOT NULL DEFAULT 0 COMMENT 'Overall quality score, 0-100',
  `character_consistency_score` int NOT NULL DEFAULT 0 COMMENT 'Character consistency score, 0-100',
  `visual_quality_score` int NOT NULL DEFAULT 0 COMMENT 'Visual quality score, 0-100',
  `motion_continuity_score` int NOT NULL DEFAULT 0 COMMENT 'Motion and continuity score, 0-100',
  `audio_readiness_score` int NOT NULL DEFAULT 0 COMMENT 'Dialogue/audio readiness score, 0-100',
  `verdict` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'review' COMMENT 'pass/review/reject',
  `issue_summary` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Readable issue summary',
  `suggestion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'Improvement suggestion',
  `selected` tinyint NOT NULL DEFAULT 0 COMMENT 'Whether this candidate is selected for storyboard item',
  `reviewer_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'auto_rule' COMMENT 'auto_rule/agent/manual',
  `score_details` json NULL COMMENT 'Explainable score details',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_sb_video_quality_item` (`storyboard_item_id` ASC) USING BTREE,
  INDEX `idx_sb_video_quality_video_item` (`video_item_id` ASC) USING BTREE,
  INDEX `idx_sb_video_quality_selected` (`storyboard_item_id` ASC, `selected` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Storyboard video quality review results' ROW_FORMAT = Dynamic;
