"use client";
import { useEffect,useState } from "react";
import { Copy,Loader2,Pencil,Plus,Save,Trash2,X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { videoTemplateApi,type EditableVideoTemplate,type VideoTemplateRecord } from "@/lib/video-templates";
const EMPTY=JSON.stringify({duration:60,aspectRatio:"9:16",projectType:"短剧",storyPrompt:"",negativePrompt:[],camera:{perspective:"first_person_pov",device:"handheld_phone",style:[]},voiceover:{enabled:true,person:"first",tone:"",maxSentenceLength:18,bgmDuckDb:-6},audio:{bgmUrl:"",bgmVolume:.34,originalAudioVolume:.18},beats:[]},null,2);
const blank=():EditableVideoTemplate=>({code:"",name:"",category:"通用",description:"",coverUrl:null,configJson:EMPTY,status:0,sortOrder:0});
export default function Page(){const[items,setItems]=useState<VideoTemplateRecord[]>([]),[form,setForm]=useState<EditableVideoTemplate|null>(null),[editingId,setEditingId]=useState<number>(),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
async function load(){setLoading(true);try{setItems(await videoTemplateApi.listRecords(false))}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
function edit(i:VideoTemplateRecord){setEditingId(i.id);setForm({code:i.code,name:i.name,category:i.category,description:i.description,coverUrl:i.coverUrl,configJson:JSON.stringify(JSON.parse(i.configJson),null,2),status:i.status,sortOrder:i.sortOrder});setError("")}
async function save(){if(!form)return;setSaving(true);setError("");try{JSON.parse(form.configJson);if(editingId)await videoTemplateApi.update(editingId,form);else await videoTemplateApi.create(form);setForm(null);setEditingId(undefined);await load()}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setSaving(false)}}
async function remove(id:number){if(!confirm("确定删除这个模板吗？已创建项目中的模板快照不会受影响。"))return;await videoTemplateApi.delete(id);await load()}
return <div className="mx-auto max-w-6xl space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">视频模板</h1><p className="mt-1 text-sm text-muted-foreground">管理项目创建、故事生成、镜头节拍和固定音频配置。</p></div><Button onClick={()=>{setEditingId(undefined);setForm(blank())}}><Plus/>新建模板</Button></div>
{form&&<section className="border-y bg-muted/10 py-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">{editingId?"编辑模板":"新建模板"}</h2><Button variant="ghost" size="icon-sm" onClick={()=>setForm(null)}><X/></Button></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs text-muted-foreground">名称<Input className="mt-1" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="text-xs text-muted-foreground">唯一编码<Input className="mt-1" disabled={!!editingId} value={form.code} onChange={e=>setForm({...form,code:e.target.value.replace(/[^a-z0-9-_]/g,"")})}/></label><label className="text-xs text-muted-foreground">分类<Input className="mt-1" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="text-xs text-muted-foreground">排序<Input className="mt-1" type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:+e.target.value})}/></label><label className="text-xs text-muted-foreground md:col-span-2">描述<Input className="mt-1" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="text-xs text-muted-foreground">状态<select className="mt-1 h-9 w-full rounded-md border bg-background px-2" value={form.status} onChange={e=>setForm({...form,status:+e.target.value})}><option value={0}>草稿</option><option value={1}>已发布</option><option value={2}>已停用</option></select></label><label className="text-xs text-muted-foreground">封面 URL<Input className="mt-1" value={form.coverUrl||""} onChange={e=>setForm({...form,coverUrl:e.target.value||null})}/></label><label className="text-xs text-muted-foreground md:col-span-2">高级配置 JSON<textarea className="mt-1 min-h-80 w-full rounded-md border bg-background p-3 font-mono text-xs outline-none focus:border-primary" value={form.configJson} onChange={e=>setForm({...form,configJson:e.target.value})}/></label></div>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}<div className="mt-4 flex justify-end"><Button disabled={saving} onClick={save}>{saving?<Loader2 className="animate-spin"/>:<Save/>}保存模板</Button></div></section>}
{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin"/></div>:<div className="divide-y border-y">{items.map(i=><div key={i.id} className="flex items-center gap-4 py-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-medium">{i.name}</h3><span className={i.status===1?"text-xs text-emerald-500":"text-xs text-muted-foreground"}>{i.status===0?"草稿":i.status===1?"已发布":"已停用"}</span><span className="text-xs text-muted-foreground">v{i.version}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{i.category} · {i.code} · {i.description}</p></div><Button variant="ghost" size="icon-sm" title="复制" onClick={()=>{setEditingId(undefined);setForm({...blank(),code:`${i.code}-copy`,name:`${i.name} 副本`,category:i.category,description:i.description,coverUrl:i.coverUrl,configJson:JSON.stringify(JSON.parse(i.configJson),null,2),sortOrder:i.sortOrder})}}><Copy/></Button><Button variant="ghost" size="icon-sm" title="编辑" onClick={()=>edit(i)}><Pencil/></Button><Button variant="destructive" size="icon-sm" title="删除" onClick={()=>void remove(i.id)}><Trash2/></Button></div>)}</div>}</div>}
